/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElTree: typeof import('element-plus/es')['ElTree']
    Graph: typeof import('./src/components/Graph.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
